#!/usr/bin/env bun
/**
 * OpenAPI Code Generation Script
 *
 * Fetches the Stromboli OpenAPI spec and generates TypeScript types + client
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import openapiTS from 'openapi-typescript'

const GENERATED_DIR = join(import.meta.dir, '..', 'src', 'generated')

interface PackageJson {
  stromboli: {
    apiVersion: string
    apiVersionRange: string
  }
}

async function getApiVersion(): Promise<string> {
  const pkg = (await Bun.file(join(import.meta.dir, '..', 'package.json')).json()) as PackageJson
  return pkg.stromboli.apiVersion
}

function getSwaggerUrl(version: string): string {
  return `https://raw.githubusercontent.com/tomblancdev/stromboli/v${version}/docs/swagger/swagger.yaml`
}

async function fetchSpec(url: string): Promise<string> {
  console.log(`📥 Fetching OpenAPI spec from: ${url}`)

  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`Failed to fetch spec: ${response.status} ${response.statusText}`)
  }

  return response.text()
}

async function generateTypes(specContent: string): Promise<string> {
  console.log('🔧 Generating TypeScript types...')

  const output = await openapiTS(specContent, {
    exportType: true,
    pathParamsAsTypes: true,
  })

  return output
}

function generateApiClient(): string {
  console.log('🔧 Generating API client...')

  return `/**
 * Auto-generated API client for Stromboli
 * DO NOT EDIT - generated by scripts/generate.ts
 */

import createClient from 'openapi-fetch'
import type { paths } from './types'

export type StromboliApiClient = ReturnType<typeof createClient<paths>>

export function createStromboliClient(baseUrl: string): StromboliApiClient {
  return createClient<paths>({ baseUrl })
}
`
}

async function main(): Promise<void> {
  try {
    // Get API version from package.json
    const apiVersion = await getApiVersion()
    console.log(`📦 Target Stromboli API version: v${apiVersion}`)

    // Fetch OpenAPI spec
    const swaggerUrl = getSwaggerUrl(apiVersion)
    const specContent = await fetchSpec(swaggerUrl)

    // Ensure generated directory exists
    await mkdir(GENERATED_DIR, { recursive: true })

    // Generate and write types
    const types = await generateTypes(specContent)
    const typesPath = join(GENERATED_DIR, 'types.ts')
    await writeFile(typesPath, types)
    console.log(`✅ Generated: ${typesPath}`)

    // Generate and write API client
    const apiClient = generateApiClient()
    const apiPath = join(GENERATED_DIR, 'api.ts')
    await writeFile(apiPath, apiClient)
    console.log(`✅ Generated: ${apiPath}`)

    console.log('🎉 Code generation complete!')
  } catch (error) {
    console.error('❌ Generation failed:', error)
    process.exit(1)
  }
}

main()
